name: Deploy backend of the PMS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build Docker image
      run: docker build -t chathuratd007/pms_back .

    - name: Push Docker image
      run: docker push chathuratd007/pms_back:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull chathuratd007/pms_back:latest

    - name: Stop existing Docker container (if running)
      run: docker stop pms_back || true

    - name: Remove existing Docker container (if exists)
      run: docker rm pms_back || true

    - name: Run Docker container in production
      run: |
        docker run -d -p 4000:4000 \
          -e "MONGO_URI=${{ secrets.MONGO_URI }}" \
          -e "SECRET=${{ secrets.SECRET }}" \
          -e "REACT_APP_PROD_BASE_URL"="${{ secrets.REACT_APP_PROD_BASE_URL }}" \
          -e "PORT=4000" \
          --name pms_back \
          chathuratd007/pms_back:latest
